---
title: "Resume"
---

# 
Technical Skills

| Type            | Skills                                                                                    |
|-----------------|-------------------------------------------------------|
| Languages       | Java, Python, C/C++, SQL (Postgres), JavaScript, HTML/CSS, R, LaTeX, Bash, Shell          |
| Frameworks      | Node.js, Pytest, Unittest, JUnit, WordPress                                               |
| Developer Tools | Git, VS Code, Visual Studio, Oracle, PyCharm, IntelliJ, Eclipse, Unity, Java 8+, MS Excel |
| Libraries       | pandas, NumPy, Matplotlib, React, GNU C, Standard C libraries                             |

# 
Education

University of Toronto Canada
Bachelor of Science in Statistics and Economics, Minor in Computer Science Sep. 2021 – April 2025
Relevant Coursework: Data Analysis, Machine Learning, DSA, Advanced Programming, Probability
Introduction to Game Development in Python Toronto, CAN
GameDev Certification Program teaching game development using Python programming language. May. 2021 – Sep 2021
DEERHACKS III Hackathon Toronto, CAN
Developed an algorithm to eradicate phantom traffic. The DevPost for the project can be found here: [Link](https://devpost.com/software/intelliflow-b8qcl7)

# 
Experience

Programming Instructor/Sensei May 2023 – Sept 2023
Code Ninjas \| JavaScript, C #, Unity, Block, MakeCode, SpringBoot, MongoDB Brampton, ONT
• Organized and executed a Hackathon targeting children aged 8-14, creating coding enthusiasm in the tech industry.
• Facilitated a seamless transition from Scratch coding/GDP JavaScript to MS Makecode (IMPACT) upon the
collaboration with Microsoft. This led to a 25% increase in the number of students joining the institution.
• Instructed children in coding, Mathematics, and robotics, learning adaptability and problem-solving skills.

Facilitated Study Group Leader Jan. 2022 – Present
University of Toronto \| Communication, Collaboration, OOP, Python, Probability Mississauga, ONT
• Showcased proficiency in teaching economics concepts, coupled with advanced proficiency in Python programming.
• Taught the concepts of economic fundamentals like Supply and demand, Utility, Costs of Production, GDP,etc.
• Developed strong facilitation skills through leading group discussions and activities, while honing my ability to
communicate complex concepts and engage with the community.

# 
Projects

Data Analysis Paper on Suicide PCI Calls Event Patterns \| R, Quarto, Git, GitHub, Data Visualization
• Conducted an in-depth analysis of Toronto Police Services’ 10-year Persons in Crisis Calls dataset, revealing a
direct correlation between suicide events and factors such as time of day, day of the week, and geographic location,
aiming to enhance crisis response strategies and community well-being. Available at: [GitHub Repository](https://github.com/vanshikav2/Data_Analysis_1).

Data Analysis Paper on Student Performance COVID-19 US States Factors \| Quarto,GitHub, SSRP
• Conducted collaborative data analysis with a team of three researchers, assessing the impact of the COVID-19
pandemic on student performance in 11 U.S. states, identifying significant correlations between various factors and
learning losses, and contributing to a published paper titled ”Assessing Factors Affecting Student’s Performance
during COVID-19 Pandemic” available for replication on the Social Science Reproduction platform. Paper Github
link: [Repository Link](https://github.com/shivankgoel003/Student-Performance-COVID-19-US-States-Factors.git)

Compressor/decompressor TreeMap \| Pytest, Python, PyGame, BST/Huffman Trees/Sorting/OOP
• A file management software employing tree structures, BSTs, and Huffman trees to manipulate files through
deletion, compression, and expansion, while visually categorizing and encrypting each file based on its type.

Interactive Graphical Interfaced Boggle Game \| Unittest,UML, MVC,VS Code, Java, Git
• Led a diverse team of four programmers in the collaborative development of the Boggle Game with GUI and
various features, promoting a culture of shared learning and skill enhancement, prioritizing user accessibility with
features like eye care mode, and implementing agile methodology for efficient development.

```{r}

```
